"""Learn2Design-2026 submission: ParallelAdam — massively-parallel multi-start
Adam with Differometor-30k transplant warm starts, ES stream, and memetic selection.

Auto-generated by submission/build_submission.py. Do not edit by hand.
Bundle dataset.h5 (and canonical_index.npz if used) next to this file.
"""
from __future__ import annotations

import time
from pathlib import Path

import h5py
import jax
import jax.numpy as jnp
import numpy as np
from jaxtyping import Array, Float

from dfbench import Objective, OptimizationAlgorithm

_HERE = Path(__file__).resolve().parent
DEFAULT_DATASET = _HERE / "dataset.h5"
CANONICAL_NPZ = _HERE / "canonical_index.npz"
SURROGATE_PKL = _HERE / "surrogate_hgb.pkl"
CKEYS_DIR = _HERE / "ckeys_nonexistent"  # canonical npz is bundled instead
CACHE_PATH = _HERE / "cache_nonexistent"


import json


class _Surrogate:
    """Lazy-loaded HGB surrogate: canonical (key,value) space -> log1p(loss).

    Trained on the full Differometor-30k canonical index (28,863 entries,
    held-out-topology Spearman 0.918). Instance-independent: model and key
    columns load from bundled files, usable before start_logging; candidate
    keys are mapped at query time (post-logging)."""
    model = None
    key_to_col = None
    tried = False

    @classmethod
    def load(cls):
        if not cls.tried:
            cls.tried = True
            try:
                if SURROGATE_PKL.exists():
                    import pickle

                    with open(SURROGATE_PKL, "rb") as f:
                        cls.model = pickle.load(f)
                    d = np.load(CANONICAL_NPZ, allow_pickle=True)
                    cls.key_to_col = {str(k): i for i, k in enumerate(d["keys"])}
            except Exception:
                cls.model = None
        return cls.model


def surrogate_score(problem, Cb: np.ndarray):
    """Score bounded candidates (B,n) with the surrogate. Returns (B,) or None."""
    m = _Surrogate.load()
    if m is None:
        return None
    keys = problem_pair_keys(problem)
    cols = np.array([_Surrogate.key_to_col.get(k, -1) for k in keys])
    ok = cols >= 0
    Xc = np.full((Cb.shape[0], len(_Surrogate.key_to_col)), np.nan)
    Xc[:, cols[ok]] = Cb[:, ok]
    return m.predict(Xc)


def _pair_key(pair) -> str:
    """Canonical string key for one optimization pair (handles tied groups)."""
    return f"{repr(pair[0])}|{repr(pair[1])}"


def problem_pair_keys(problem) -> list[str]:
    return [_pair_key(p) for p in problem._optimization_pairs]


class WarmStartIndex:
    """Index over the dataset for topology-nearest warm starts."""

    def __init__(self, dataset_path: str | Path = DEFAULT_DATASET, size: int = 3):
        self.dataset_path = Path(dataset_path)
        self.size = size
        h5 = h5py.File(self.dataset_path, "r")
        entries = h5["entries"]
        losses = entries["loss"][:]
        topos = entries["topology_string"][:]
        topos = np.array([t.decode() if isinstance(t, bytes) else t for t in topos])
        sizes = entries["size"][:]
        # size=None keeps every entry (instance-independent index: the competition
        # forbids reading the problem instance before start_logging, so the index
        # must not filter by the problem's size at build time; donor size is
        # matched to the target at query time via string length instead).
        keep = np.arange(len(sizes)) if size is None else np.where(sizes == size)[0]
        order = keep[np.argsort(losses[keep], kind="stable")]
        best_idx: dict[str, int] = {}
        for i in order:
            t = topos[i]
            if t not in best_idx:
                best_idx[t] = int(i)
        self.topo_list = sorted(best_idx.keys())
        self.best_entry_idx = np.array([best_idx[t] for t in self.topo_list])
        self.best_losses = losses[self.best_entry_idx]
        # character matrix for fast Hamming (padded; other-length donors are
        # excluded at query time, so padding never affects kept distances)
        self._topo_len = np.array([len(t) for t in self.topo_list], dtype=np.int32)
        W = int(self._topo_len.max())
        self._topo_mat = np.array([list(t) + ["\0"] * (W - len(t)) for t in self.topo_list])
        self._topo_size = {t: int(sizes[i]) for t, i in best_idx.items()}
        # stash params pool lazily
        self._h5 = h5
        self._entries = entries
        self._params_pool = h5["bounded_params"]
        self._donor_cache: dict[str, tuple[np.ndarray, dict[str, float]]] = {}
        self._sens: np.ndarray | None = None
        self._key_cache = self._load_key_cache()
        self._elite_medians_computed = False
        self._elite_medians: dict | None = None

    def elite_key_medians(self) -> dict | None:
        """Global per-key median among bottom-decile-loss entries (canonical npz).

        A better fill prior than the donor's own siblings: conditional on the
        key existing, what value do ELITE entries across all topologies take?
        Computed lazily once per run (only when fill_mode="elite" is used)."""
        if self._elite_medians_computed:
            return self._elite_medians
        self._elite_medians_computed = True
        self._elite_medians = None
        try:
            if CANONICAL_NPZ.exists():
                d = np.load(CANONICAL_NPZ, allow_pickle=True)
                keys = d["keys"]
                X, M, L = d["X"], d["M"], d["L"]
                valid = M.sum(axis=1) > 0
                thr = np.percentile(L[valid], 10)
                elite = valid & (L <= thr)
                Xe, Me = X[elite], M[elite]
                cnt = Me.sum(axis=0)
                meds = {}
                for j in np.where(cnt >= 20)[0]:
                    meds[str(keys[j])] = float(np.median(Xe[Me[:, j], j]))
                self._elite_medians = meds
        except Exception:
            pass
        return self._elite_medians

    @staticmethod
    def _load_key_cache():
        """Precomputed {topology: [pair_keys]} from canonical build (avoids
        expensive UIFOProblem construction per donor). Returns None if absent."""
        import json as _json

        cache = {}
        try:
            if CANONICAL_NPZ.exists():
                d = np.load(CANONICAL_NPZ, allow_pickle=True)
                keys = [str(k) for k in d["keys"]]
                # hoist arrays out of the loop: NpzFile re-decompresses the
                # array on EVERY access (11k x 18MB otherwise) — validation
                # timeout fix flagged by the organizers (no algorithm change)
                topo_list = d["topo_list"]
                map_len = d["map_len"]
                maps = d["maps"]
                for ti, t in enumerate(topo_list):
                    ml = int(map_len[ti])
                    cache[str(t)] = [str(keys[int(i)]) for i in maps[ti, :ml]]
        except Exception:
            pass
        try:
            if CKEYS_DIR.exists():
                import hashlib

                for fp in CKEYS_DIR.glob("*.json"):
                    ks = _json.loads(fp.read_text())
                    # ckeys files are keyed by sha1(topology); we can't invert the
                    # hash, so these are only useful via canonical_index. Skip.
                    break
        except Exception:
            pass
        return cache if cache else None

    def sens_row(self, eidx: int) -> np.ndarray:
        """Lazy per-entry 50-dim spectral fingerprint — the ready-made behavior
        descriptor for niche stratification (MAP-Elites lineage, §21)."""
        if self._sens is None:
            self._sens = self._h5["sensitivities"][:]
        return self._sens[eidx]

    def close(self):
        try:
            self._h5.close()
        except Exception:
            pass

    def nearest_donors(self, topology: str, k: int = 8, interior_weight: float = 1.0,
                       loss_weight: float = 0.0, loss_floor: float = -1.0):
        """k donor topologies ranked by dist + loss_weight*max(loss, loss_floor).

        Data: random-topology NN distance ~7; deeply-optimized topologies reach
        0.17-0.42 while a median NN donor sits at 2.2 -> trading a little distance
        for much better donor loss pays off."""
        t = np.array(list(topology))
        diff = (self._topo_mat[:, : len(t)] != t[None, :]).astype(np.float32)
        if interior_weight != 1.0 and len(t) >= 9:
            w = np.ones(len(t), dtype=np.float32)
            w[:9] = interior_weight
            diff = diff * w[None, :]
        dist = diff.sum(axis=1)
        # donors must match the target's size class (topology string length);
        # other-length entries get truncated comparisons above and are masked out
        dist = np.where(self._topo_len == len(t), dist, np.inf)
        score = dist + loss_weight * np.maximum(self.best_losses, loss_floor)
        order = np.lexsort((dist, score))
        out = []
        for j in order[:k]:
            out.append((self.topo_list[j], float(dist[j]), float(self.best_losses[j]),
                        int(self.best_entry_idx[j])))
        return out

    def _donor_key_values(self, topology: str, entry_idx: int):
        """Map donor params to {pair_key: value}; key list from cache or construction."""
        if topology in self._donor_cache:
            return self._donor_cache[topology]
        e = self._entries[entry_idx]
        off, ln = int(e["param_offset"]), int(e["param_length"])
        params = np.asarray(self._params_pool[off:off + ln], dtype=np.float64)
        keys = None
        if self._key_cache is not None:
            keys = self._key_cache.get(topology)
        if keys is None:
            from dfbench.problems import UIFOProblem  # lazy
            donor_prob = UIFOProblem(size=self._topo_size.get(topology, 3), topology=topology)
            keys = problem_pair_keys(donor_prob)
        kv = {k: float(v) for k, v in zip(keys, params)}
        self._donor_cache[topology] = (params, kv)
        return self._donor_cache[topology]

    def transplant_composite(self, target_problem, donors,
                             fill: str = "donor_sibling") -> np.ndarray:
        """Multi-donor composite transplant: for each target key, copy from the
        nearest donor (ranked order) that HAS the key; still-missing keys fall
        back to the union same-property pool across donors, else midpoint.

        Rationale: single-donor transplants leave ~10% of params (the components
        where topologies differ) to heuristic fill; those params have no joint
        structure to preserve from that donor anyway, so borrowing the matching
        key from the next-nearest donor that owns it should raise fidelity.
        """
        tgt_keys = problem_pair_keys(target_problem)
        lb, ub = [np.asarray(b, dtype=np.float64) for b in target_problem.bounds]
        kvs = []
        prop_pool: dict[str, list[float]] = {}
        for topo, _dist, _dloss, eidx in donors:
            _, kv = self._donor_key_values(topo, eidx)
            kvs.append(kv)
            for k, v in kv.items():
                prop_pool.setdefault(k.split("|")[1].strip("'"), []).append(v)
        out = np.empty(len(tgt_keys), dtype=np.float64)
        n_copied = 0
        for i, k in enumerate(tgt_keys):
            val = None
            for kv in kvs:
                v = kv.get(k)
                if v is not None:
                    val = v
                    break
            if val is None:
                prop = k.split("|")[1].strip("'")
                pool = prop_pool.get(prop)
                if fill == "donor_sibling" and pool:
                    val = float(np.median(pool))
                else:
                    val = 0.5 * (lb[i] + ub[i])
            else:
                n_copied += 1
            out[i] = float(np.clip(val, lb[i], ub[i]))
        self.last_fill_ratio = n_copied / max(len(tgt_keys), 1)
        return out

    def transplant(self, target_problem, donor_topology: str, entry_idx: int,
                   fill: str = "donor_sibling", aux_kvs=None) -> np.ndarray:
        """Build a bounded param vector for target_problem from the donor entry.

        Missing keys (mostly boundary components that differ) are filled from the
        donor's same-property values at other positions (donor_sibling), else
        bounds midpoint. When aux_kvs (list of {pair_key: value} from other
        near donors) is given, a missing key is first borrowed from the nearest
        aux donor that owns it (composite fill) before the sibling heuristic.
        """
        _, donor_kv = self._donor_key_values(donor_topology, entry_idx)
        # donor property -> values pool (for sibling fill)
        prop_pool: dict[str, list[float]] = {}
        for k, v in donor_kv.items():
            prop = k.split("|")[1].strip("'")
            prop_pool.setdefault(prop, []).append(v)

        tgt_keys = problem_pair_keys(target_problem)
        lb, ub = [np.asarray(b, dtype=np.float64) for b in target_problem.bounds]
        out = np.empty(len(tgt_keys), dtype=np.float64)
        n_copied = 0
        for i, k in enumerate(tgt_keys):
            if k in donor_kv:
                out[i] = donor_kv[k]
                n_copied += 1
            else:
                val = None
                if aux_kvs:
                    for akv in aux_kvs:
                        v = akv.get(k)
                        if v is not None:
                            val = v
                            n_copied += 1
                            break
                if val is None:
                    if fill == "elite":
                        em = self.elite_key_medians()
                        if em is not None:
                            val = em.get(k)
                    if val is None:
                        prop = k.split("|")[1].strip("'")
                        pool = prop_pool.get(prop)
                        if fill != "midpoint" and pool:
                            val = float(np.median(pool))
                        else:
                            val = 0.5 * (lb[i] + ub[i])
                out[i] = val
            out[i] = float(np.clip(out[i], lb[i], ub[i]))
        self.last_fill_ratio = n_copied / max(len(tgt_keys), 1)
        return out


LOG_PROPS = {"mass", "length"}


def build_group_mapping(problem):
    """Return (unit_mapping, inverse_unit_mapping) jnp-callables for the problem."""
    keys = [repr(p[1]).strip("'") for p in problem._optimization_pairs]
    lb = np.asarray(problem.bounds[0], dtype=np.float64)
    ub = np.asarray(problem.bounds[1], dtype=np.float64)
    is_log = np.array([k in LOG_PROPS for k in keys])
    log_lb = np.log(np.maximum(lb, 1e-300))
    log_ub = np.log(np.maximum(ub, 1e-300))
    log_span = log_ub - log_lb

    is_log_j = jnp.asarray(is_log)
    lb_j = jnp.asarray(lb)
    ub_j = jnp.asarray(ub)
    log_lb_j = jnp.asarray(log_lb)
    log_span_j = jnp.asarray(log_span)

    def unit_mapping(z):
        """z (R^n) -> normalized [0,1]^n such that bounded = lb + (ub-lb)*unit."""
        s = jax_sigmoid(z)
        # log group: bounded = exp(log_lb + log_span * s) ->
        # unit = (bounded - lb)/(ub - lb)
        u_log = (jnp.exp(log_lb_j + log_span_j * s) - lb_j) / (ub_j - lb_j)
        return jnp.where(is_log_j, u_log, s)

    def inverse_unit_mapping(u):
        """normalized [0,1]^n -> z in R^n (logit of the group's internal s)."""
        u = jnp.clip(u, 1e-12, 1 - 1e-12)
        bounded = lb_j + (ub_j - lb_j) * u
        s_log = (jnp.log(jnp.maximum(bounded, 1e-300)) - log_lb_j) / log_span_j
        s_log = jnp.clip(s_log, 1e-12, 1 - 1e-12)
        s = jnp.where(is_log_j, s_log, u)
        return jnp.log(s / (1 - s))

    return unit_mapping, inverse_unit_mapping


def jax_sigmoid(x):
    return 1.0 / (1.0 + jnp.exp(-x))


def _position_groups(pairs) -> np.ndarray:
    """Group param indices by first grid position found in the component name(s)."""
    import re

    groups = {}
    gids = np.zeros(len(pairs), dtype=np.int32)
    for i, pr in enumerate(pairs):
        comp = repr(pr[0])
        toks = re.findall(r"\d{2}", comp)
        g = toks[0] if toks else "zz"
        if g not in groups:
            groups[g] = len(groups)
        gids[i] = groups[g]
    return gids


class ParallelAdamSubmission(OptimizationAlgorithm):
    algorithm_str = "parallel_adam"
    algorithm_type = None

    def __init__(
        self,
        n_chains: int = 128,
        n_transplant: int = 8,
        chunk_size: int = 8,
        lr: float = 0.05,
        lr_final_frac: float = 0.1,
        decay_onset: float = 0.0,
        noise0: float = 0.05,
        noise_final: float = 0.005,
        noise_decay_prog: float = 0.3,
        select_fracs=(0.45, 0.7),
        select_keep_frac: float = 0.5,
        betas=(0.9, 0.99),
        eps: float = 1e-8,
        grad_clip: float = 1.0,
        dataset_path: str | None = None,
        interior_weight: float = 1.0,
        phase_log_every: int = 50,
        reparam: bool = False,
        penalty: str = "default",
        es_frac: float = 0.0,
        es_top_m: int = 8,
        es_sigma0: float = 0.3,
        es_sigma_min: float = 0.01,
        es_sigma_max: float = 0.6,
        extreme_init: bool = False,
        extreme_beta: float = 0.3,
        crossover_frac: float = 0.0,
        donor_loss_weight: float = 0.0,
        composite_fill: int = 0,
        kick_patience: int = 0,
        kick_patience_prog: float = 0.0,
        kick_max_prog: float = 1.0,
        kick_frac: float = 0.34,
        kick_donor_pool: int = 64,
        kick_sigma: float = 0.7,
        kick_sigma_list: tuple = (),
        kick_schedule: tuple = (),
        kick_protect_prog: float = 0.0,
        kick_diverse: bool = False,
        kick_mode: str = "donor",
        elite_hop_sigma: float = 1.5,
        screen_pool: int = 0,
        screen_chunk: int = 32,
        polish_start: float = 0.0,
        select_rule: str = "current",
        select_keep_moments: bool = False,
        init_niche: str = "",
        deme2_frac: float = 0.0,
        deme2_kick_schedule: tuple = (),
        deme2_adaptive: bool = False,
        deme_select: str = "global",
        deme2_cull_frac: float = 0.0,
        deme2_kick_elite: bool = False,
        tr_window_prog: float = 0.0,
        tr_lo: float = 0.5,
        tr_hi: float = 2.0,
        tr_grow: float = 1.15,
        tr_shrink: float = 0.85,
        screen_cascade: int = 0,
        screen_diverse: int = 0,
        screen_fp: str = "",
        kick_novelty: bool = False,
        kick_max_prog_novel: float = 0.0,
        polyak_ema: float = 0.0,
        polyak_cadence: float = 0.02,
        resume_prog_fix: bool = False,
        sigma_ladder: float = 0.0,
        kick_roi_gate: bool = False,
        kick_roi_backoff: float = 2.0,
        kick_roi_cap: float = 8.0,
        kick_patience_stretch: float = 0.0,
        fill_mode: str = "donor_sibling",
        restart_fracs: tuple = (),
        restart_lr_frac: float = 0.6,
        surr_screen: int = 0,
        surr_kick: int = 0,
        surr_keep_frac: float = 0.0,
    ):
        self.fill_mode = fill_mode
        self.restart_fracs = tuple(restart_fracs)
        self.restart_lr_frac = restart_lr_frac
        self.surr_screen = surr_screen
        self.surr_kick = surr_kick
        self.surr_keep_frac = surr_keep_frac
        self.n_chains = n_chains
        self.n_transplant = n_transplant
        self.lr = lr
        self.lr_final_frac = lr_final_frac
        self.decay_onset = decay_onset
        self.noise0 = noise0
        self.noise_final = noise_final
        self.noise_decay_prog = noise_decay_prog
        self.select_fracs = tuple(select_fracs)
        self.select_keep_frac = select_keep_frac
        self.b1, self.b2 = betas
        self.eps = eps
        self.chunk_size = chunk_size
        self.grad_clip = grad_clip
        self.dataset_path = dataset_path or str(DEFAULT_DATASET)
        self.interior_weight = interior_weight
        self.phase_log_every = phase_log_every
        self.reparam = reparam
        self.penalty = penalty
        self.es_frac = es_frac
        self.es_top_m = es_top_m
        self.es_sigma0 = es_sigma0
        self.es_sigma_min = es_sigma_min
        self.es_sigma_max = es_sigma_max
        self._es_sigma = es_sigma0
        self.extreme_init = extreme_init
        self.extreme_beta = extreme_beta
        self.crossover_frac = crossover_frac
        self.donor_loss_weight = donor_loss_weight
        self.composite_fill = composite_fill
        self.kick_patience = kick_patience
        self.kick_patience_prog = kick_patience_prog
        self.kick_max_prog = kick_max_prog
        self.kick_frac = kick_frac
        self.kick_donor_pool = kick_donor_pool
        self.kick_sigma = kick_sigma
        self.kick_sigma_list = tuple(kick_sigma_list)
        self.kick_schedule = tuple(kick_schedule)
        self._kick_sched_idx = 0
        self.kick_protect_prog = kick_protect_prog
        self._chain_kick_prog = None  # per-chain prog of last kick (run-init, B-sized)
        self.kick_diverse = kick_diverse
        self.kick_mode = kick_mode
        self.elite_hop_sigma = elite_hop_sigma
        self.screen_pool = screen_pool
        self.screen_chunk = screen_chunk
        self.screen_diverse = screen_diverse
        self.screen_fp = screen_fp
        self.polish_start = polish_start
        self.select_rule = select_rule
        self.select_keep_moments = select_keep_moments
        self.init_niche = init_niche
        self.deme2_frac = deme2_frac
        self.deme2_kick_schedule = tuple(deme2_kick_schedule)
        self.deme2_adaptive = deme2_adaptive
        self.deme_select = deme_select
        self.deme2_cull_frac = deme2_cull_frac
        self.deme2_kick_elite = deme2_kick_elite
        self._deme1 = None  # bool mask (B,), True = deme 1 (regime-B chains)
        self._gb_prev_d = [np.inf, np.inf]
        self._last_improve_prog_d = [0.0, 0.0]
        self._kick_sched_idx_d2 = 0
        self.tr_window_prog = tr_window_prog
        self.tr_lo = tr_lo
        self.tr_hi = tr_hi
        self.tr_grow = tr_grow
        self.tr_shrink = tr_shrink
        self._lr_mult = None
        self._tr_ref = None
        self._tr_last_prog = -1e9
        self._chain_hist: list = []  # (prog, best_merit snapshot) for extrap selection
        self.screen_cascade = screen_cascade
        self.kick_novelty = kick_novelty
        self.kick_max_prog_novel = kick_max_prog_novel
        self._donor_used: dict = {}  # (topo,eidx) -> injection count (novelty bookkeeping)
        self.polyak_ema = polyak_ema
        self.polyak_cadence = polyak_cadence
        self._ema_prev_prog = 0.0
        self._ema_eval_prog = -1.0
        self.resume_prog_fix = resume_prog_fix
        self._obj_max_time = 0.0
        self.sigma_ladder = sigma_ladder
        # realized-payoff kick gate (v30): consecutive kicks that failed to move
        # the global best stretch the effective patience geometrically, breaking
        # the far-donor failure spiral (kicks refiring every base patience while
        # gb stays frozen) without touching seeds where kicks keep paying.
        self.kick_roi_gate = kick_roi_gate
        self.kick_roi_backoff = kick_roi_backoff
        self.kick_roi_cap = kick_roi_cap
        # data-fitted smooth kick-budget decay (v38): patience stretches as
        # (1 + stretch*prog) — front-loads kicks when basin coverage is fresh and
        # lets them die out as the measured hit-rate decays geometrically (§11c/d).
        self.kick_patience_stretch = kick_patience_stretch
        self._kick_roi_fails = 0
        self._gb_at_last_kick = np.inf
        self._ws_index = None
        self._traj = []
        self._donor_cycle = 0
        self._last_improve_step = 0
        self._last_improve_prog = 0.0
        self._global_best_prev = np.inf
        self._groups = None  # component-position group id per param (for crossover)
        self.phase_log: list[str] = []
        self._ckpt_path = None
        self._ckpt_interval = 45.0
        self._ckpt_last = 0.0
        self._resume_from = None
        self.cum_time_prev = 0.0

    def set_checkpointing(self, path: str, interval_s: float = 45.0):
        self._ckpt_path = path
        self._ckpt_interval = interval_s

    def request_resume(self, path: str):
        self._resume_from = path

    def _save_ckpt(self, X, m, v, best_x, best_merit, step, selected, key, cum_time,
                   ema_x=None):
        if not self._ckpt_path:
            return
        import os
        import tempfile

        fd, tmp = tempfile.mkstemp(dir=os.path.dirname(self._ckpt_path), suffix=".npz")
        os.close(fd)
        extra = {}
        if ema_x is not None:
            extra["ema_x"] = np.asarray(ema_x)
        if self._lr_mult is not None:
            extra["lr_mult"] = np.asarray(self._lr_mult)
        np.savez(tmp,
                 X=np.asarray(X), m=np.asarray(m), v=np.asarray(v),
                 best_x=best_x, best_merit=best_merit,
                 best_feasible=np.array([self.best_feasible_loss_algo]),
                 step=np.array([step]), es_sigma=np.array([self._es_sigma]),
                 selected=np.array(sorted(selected)),
                 key_data=np.asarray(jax.random.key_data(key)),
                 cum_time=np.array([cum_time]),
                 kick_roi=np.array([self._kick_roi_fails, self._gb_at_last_kick,
                                    self._kick_sched_idx, self._kick_sched_idx_d2]),
                 chain_kick_prog=(self._chain_kick_prog if self._chain_kick_prog is not None
                                  else np.zeros(0)),
                 traj=np.array(self._traj) if self._traj else np.zeros((0, 2)),
                 phase_log=np.array(self.phase_log, dtype=object), **extra)
        os.replace(tmp, self._ckpt_path)

    # --------------------------------------------------------------- helpers
    def _load_index(self, obj: Objective):
        """Instance-independent: load the dataset index (no objective info used).

        size=None: the index covers all size classes and donors are matched by
        topology-string length at query time, so nothing is read from the
        evaluation problem before start_logging (submission-rules compliance).
        """
        if self.n_transplant <= 0 or not Path(self.dataset_path).exists():
            return None
        try:
            return WarmStartIndex(self.dataset_path, size=None)
        except Exception as e:
            self.phase_log.append(f"index_load_failed: {e!r}")
            return None

    def _aux_kvs(self, ws, donors):
        """{pair_key: value} dicts of the first composite_fill donors (for fill)."""
        if self.composite_fill <= 0:
            return None
        out = []
        for topo, _d, _l, eidx in donors[: self.composite_fill]:
            try:
                out.append(ws._donor_key_values(topo, eidx)[1])
            except Exception:
                continue
        return out or None

    def _extrap_score(self, cur: np.ndarray, prog: float) -> np.ndarray:
        """Freeze-thaw selection score: predicted end-of-budget merit per chain.

        Robust (Theil-Sen median) slope of best_merit vs log(prog) over the
        recent history window; predicted_final = cur + slope*(log(1)-log(prog)).
        Chains still improving get credit for unrealized progress, protecting
        late-blooming basins from hard halving. Falls back to current merit
        when history is insufficient (e.g. right after a resume).
        """
        pts = [(p, m) for p, m in self._chain_hist if p < prog - 0.02]
        if len(pts) < 5 or prog >= 0.97:
            return cur
        w = pts[-max(4, (2 * len(pts)) // 5):]
        lp = np.log(np.array([p for p, _ in w], dtype=np.float64))
        M = np.stack([np.asarray(m, dtype=np.float64) for _, m in w])  # (T, B)
        dl = np.diff(lp)
        dl[np.abs(dl) < 1e-9] = 1e-9
        slopes = np.diff(M, axis=0) / dl[:, None]
        slope = np.median(slopes, axis=0)
        slope = np.minimum(slope, 0.0)     # never trust a worsening trend
        pred = cur - slope * np.log(prog)  # log(1.0) = 0
        pred = np.maximum(pred, cur - 1.0)  # cap extrapolation credit
        hopeless = ~np.isfinite(cur) | (cur >= 1e3)
        pred[hopeless] = cur[hopeless]
        return pred

    @staticmethod
    def _fp_from_aux(a) -> np.ndarray:
        """Behavioral fingerprint from the free aux of a value-only eval:
        asinh(power_values hard/soft/detector) + asinh(violations) (§27).
        Returns (chunk, F) float64, or None if the aux shape surprises us."""
        try:
            pv = a["power_values"]
            blocks = []
            for k in ("hard", "soft", "detector"):
                arr = np.asarray(pv[k], dtype=np.float64)
                blocks.append(np.arcsinh(arr.reshape(arr.shape[0], -1)))
            viol = np.asarray(a["violations"], dtype=np.float64)
            blocks.append(np.arcsinh(viol.reshape(viol.shape[0], -1)))
            return np.concatenate(blocks, axis=1)
        except Exception:
            return None

    def _merit_chunked(self, obj, Cj, collect_fp: bool = False):
        """Chunked value-only merit eval; updates best_feasible (logged evals).
        With collect_fp, also return the per-candidate behavioral fingerprints."""
        merits = []
        fps = [] if collect_fp else None
        for i in range(0, Cj.shape[0], self.screen_chunk):
            l, a = obj.vmap_value_aux(Cj[i : i + self.screen_chunk])
            ln = np.asarray(l, dtype=np.float64)
            fn = np.asarray(a["is_feasible"], dtype=bool)
            pn = np.asarray(a["penalty"], dtype=np.float64)
            mm = np.where(fn, ln, 1e3 + pn)
            merits.append(np.where(np.isfinite(mm), mm, np.inf))
            if collect_fp:
                fps.append(self._fp_from_aux(a))
            f_ok = fn & np.isfinite(ln)
            if np.any(f_ok):
                self.best_feasible_loss_algo = min(self.best_feasible_loss_algo,
                                                   float(np.min(ln[f_ok])))
        M = np.concatenate(merits)
        if not collect_fp:
            return M
        if any(f is None for f in fps):
            return M, None
        return M, np.concatenate(fps)

    def _screen_once(self, obj, base: np.ndarray, rng, pool: int, sigmas,
                     collect_fp: bool = False):
        """One screening pass: jitter base points at the given sigmas up to
        `pool` candidates, value-only eval in chunks, return (C, merits)
        or (C, merits, fps) when collect_fp."""
        n = base.shape[1]
        n_jit = pool - base.shape[0]
        parts = [base]
        for sig in sigmas:
            k = n_jit // len(sigmas)
            parts.append(base[rng.integers(0, base.shape[0], size=k)]
                         + sig * rng.standard_normal((k, n)))
        C = np.concatenate(parts, axis=0)[:pool]
        if not collect_fp:
            return C, self._merit_chunked(obj, jnp.asarray(C))
        M, F = self._merit_chunked(obj, jnp.asarray(C), collect_fp=True)
        return C, M, F

    def _pick_donor(self, donors):
        """Next donor index. With kick_novelty, cycle within the least-used tier
        (coupon-collector bookkeeping: re-covering visited basins is the dominant
        restart waste — de Nobel et al. PPSN 2024)."""
        if not self.kick_novelty:
            self._donor_cycle += 1
            return self._donor_cycle % len(donors)
        counts = [self._donor_used.get((t, e), 0) for t, _d, _l, e in donors]
        mn = min(counts)
        tier = [i for i, c in enumerate(counts) if c == mn]
        self._donor_cycle += 1
        return tier[self._donor_cycle % len(tier)]

    def _mark_donor(self, donor):
        if self.kick_novelty:
            t, _d, _l, e = donor
            self._donor_used[(t, e)] = self._donor_used.get((t, e), 0) + 1

    def _ksig(self, j: int) -> float:
        """Per-injection kick sigma: TuRBO-style portfolio rotation when
        kick_sigma_list is set (one kick buys fidelity and escape tickets at
        once); scalar kick_sigma otherwise (default path bit-identical)."""
        if self.kick_sigma_list:
            return float(self.kick_sigma_list[j % len(self.kick_sigma_list)])
        return self.kick_sigma

    def _build_starts(self, obj: Objective, key, ws=None) -> np.ndarray:
        """Return (B, n) bounded starts: transplants + uniform random."""
        n = obj.n_params
        lb, ub = [np.asarray(b, dtype=np.float64) for b in obj.bounds]
        starts = []
        if ws is not None:
            try:
                donors = ws.nearest_donors(obj._problem.topology_string,
                                           k=self.n_transplant,
                                           interior_weight=self.interior_weight,
                                           loss_weight=self.donor_loss_weight)
                if self.init_niche == "spec5" and donors:
                    # spectral-niche stratification of the init donors: 5 bands by
                    # argmax of the 50-dim sensitivity fingerprint, round-robin
                    # across bands (within-band loss order preserved) so the first
                    # n_chains starts span behavior space rather than piling into
                    # the single best-scoring niche (MAP-Elites lineage, §21/§19d).
                    bands: dict[int, list] = {}
                    for dnr in donors:
                        band = int(np.argmax(ws.sens_row(dnr[3])) // 10)
                        bands.setdefault(band, []).append(dnr)
                    ordered = []
                    bi = 0
                    while len(ordered) < len(donors):
                        progressed = False
                        for band in sorted(bands):
                            if bi < len(bands[band]):
                                ordered.append(bands[band][bi])
                                progressed = True
                        if not progressed:
                            break
                        bi += 1
                    donors = ordered
                aux = self._aux_kvs(ws, donors)
                for topo, dist, dloss, eidx in donors:
                    v = ws.transplant(obj._problem, topo, eidx, fill=self.fill_mode, aux_kvs=aux)
                    starts.append(v)
                    self.phase_log.append(
                        f"donor dist={dist:.0f} loss={dloss:.3f} fill={ws.last_fill_ratio:.2f} topo={topo}")
            except Exception as e:  # never let warm start kill the run
                self.phase_log.append(f"warmstart_failed: {e!r}")
        # --- surrogate pre-filter: expand all transplants into a large bounded
        # candidate pool, score with the surrogate (free, CPU), keep a diverse
        # top-n_chains. Replaces donor-rank truncation with predicted quality.
        if self.surr_screen > 0 and ws is not None and len(starts) > 0:
            try:
                t_ss = time.perf_counter()
                base = np.asarray(starts, dtype=np.float64)
                span = ub - lb
                rng2 = np.random.default_rng(1234)
                parts = [base]
                remain = self.surr_screen - len(base)
                for sig in (0.03, 0.1, 0.3):
                    k = remain // 3
                    idx = rng2.integers(0, len(base), size=k)
                    jb = base[idx] + sig * span[None, :] * rng2.standard_normal((k, base.shape[1]))
                    parts.append(np.clip(jb, lb, ub))
                Cb = np.concatenate(parts)
                sc = surrogate_score(obj._problem, Cb)
                if sc is not None:
                    # hybrid (surr_keep_frac>0): keep the top raw transplants
                    # as insurance — the surrogate over-trusts its own error on
                    # jittered points (seed-105 lesson: pred 0.013, true 0.426),
                    # so proven donor starts must survive to the real-eval
                    # screen; only the remaining slots go to surrogate picks.
                    n_keep = min(int(round(self.n_chains * self.surr_keep_frac)),
                                 len(base), self.n_chains)
                    n_surr = self.n_chains - n_keep
                    short = np.argsort(sc)[: max(n_surr * 4, 64)]
                    Cn = (Cb[short] - lb[None, :]) / span[None, :]
                    chosen = [0]
                    dmin = np.linalg.norm(Cn - Cn[0][None, :], axis=1)
                    while len(chosen) < n_surr:
                        j = int(np.argmax(dmin))
                        chosen.append(j)
                        dmin = np.minimum(dmin, np.linalg.norm(Cn - Cn[j][None, :], axis=1))
                    picks = list(Cb[short[np.asarray(chosen)]])
                    starts = list(base[:n_keep]) + picks
                    self.phase_log.append(
                        f"surr_screen: {len(Cb)} cands -> keep {n_keep} raw + {len(picks)} surr "
                        f"in {time.perf_counter()-t_ss:.0f}s, pred_best={sc[short[0]]:.3f}")
            except Exception as e:  # noqa
                self.phase_log.append(f"surr_screen_failed: {e!r}")
        rng = np.random.default_rng(int(jax.random.bits(key)))
        n_fill = self.n_chains - len(starts)
        if n_fill > 0:
            if self.extreme_init:
                # boundary-biased sampling: optima saturate bounds (bimodal physics);
                # angles/tunings stay uniform (periodic variables).
                props = [repr(p[1]).strip("'") for p in obj._problem._optimization_pairs]
                is_angle = np.array([pr in ("tuning", "angle") for pr in props])
                u = rng.beta(self.extreme_beta, self.extreme_beta, size=(n_fill, len(lb)))
                ru = rng.uniform(size=(n_fill, len(lb)))
                u = np.where(is_angle[None, :], ru, u)
                starts.extend(lb[None, :] + (ub - lb)[None, :] * u)
            else:
                for _ in range(n_fill):
                    starts.append(rng.uniform(lb, ub))
        return np.asarray(starts[: self.n_chains], dtype=np.float64)

    @staticmethod
    def _chunked_vg_aux(obj: Objective, X, chunk_size: int):
        """vmap_value_and_grad_aux over X in memory-safe chunks."""
        B = X.shape[0]
        losses, grads, feas, pens = [], [], [], []
        for i in range(0, B, chunk_size):
            l, g, a = obj.vmap_value_and_grad_aux(X[i : i + chunk_size])
            losses.append(l)
            grads.append(g)
            feas.append(a["is_feasible"])
            pens.append(a["penalty"])
        return (jnp.concatenate(losses), jnp.concatenate(grads),
                jnp.concatenate(feas), jnp.concatenate(pens))

    # ------------------------------------------------------------------ main
    def optimize(self, objective: Objective, init_params=None, random_seed=None, **kw):
        obj = objective
        # Per-run state reset: the eval runner may reuse ONE algorithm instance
        # across all 10 hidden topologies; __init__ state must not bleed between
        # runs (e.g. cum_time_prev would otherwise corrupt budget-prog scheduling
        # from the second topology on). Harness-set knobs (_ckpt_path/_resume_from)
        # are preserved; the resume fast-path below re-establishes its own state.
        self._traj = []
        self._donor_cycle = 0
        self._last_improve_step = 0
        self._last_improve_prog = 0.0
        self._global_best_prev = np.inf
        self._donor_used = {}
        self._chain_hist = []
        self._kick_roi_fails = 0
        self._gb_at_last_kick = np.inf
        self._kick_sched_idx = 0
        self._chain_kick_prog = np.full(self.n_chains, -1e9)
        self._ema_prev_prog = 0.0
        self._ema_eval_prog = -1.0
        self._obj_max_time = 0.0
        self._ckpt_last = 0.0
        self.cum_time_prev = 0.0
        self._groups = None
        self.phase_log = []
        self.best_feasible_loss_algo = np.inf
        self._es_sigma = self.es_sigma0
        if hasattr(self, "_sig_scale"):
            del self._sig_scale
        self.prepare(obj, unbounded=True, random_seed=random_seed)
        key = jax.random.PRNGKey(0 if random_seed is None else random_seed)

        # --- optional: custom per-group reparameterization (log for mass/length) ---
        if self.reparam:
            from algos.reparam import build_group_mapping

            f, finv = build_group_mapping(obj._problem)
            obj.set_space_mode(True, unit_mapping=f, inverse_unit_mapping=finv)
        else:
            # default sigmoid forward, but a *tight* inverse (clip 1e-12 vs the
            # library's 1e-7): boundary-saturated params (lengths at 0.1/4000 m)
            # must survive the z round-trip at sub-wavelength precision.
            def _tight_inv(u):
                u = jnp.clip(u, 1e-12, 1.0 - 1e-12)
                return jnp.log(u / (1.0 - u))

            obj.set_space_mode(True, unit_mapping=jax.nn.sigmoid, inverse_unit_mapping=_tight_inv)

        # --- optional: swap penalty function (search dynamics only; scoring unaffected) ---
        if self.penalty != "default":
            from dfbench.problems import relu_penalty, zero_penalty, squashed_relu_penalty

            fn = {"relu": relu_penalty, "zero": zero_penalty,
                  "squashed": squashed_relu_penalty}[self.penalty]
            obj.set_penalty_fn(fn)

        # bounded (B,n) numpy -> unbounded z (jnp) via the ACTIVE inverse mapping
        if self.reparam:
            lb_j, ub_j = jnp.asarray(obj.bounds[0]), jnp.asarray(obj.bounds[1])
            from algos.reparam import build_group_mapping

            _, finv = build_group_mapping(obj._problem)

            def _to_unbounded(b_np):
                u = (jnp.asarray(b_np) - lb_j) / (ub_j - lb_j)
                return finv(u)
        else:
            def _to_unbounded(b_np):
                lb_j = jnp.asarray(obj.bounds[0])
                ub_j = jnp.asarray(obj.bounds[1])
                u = (jnp.asarray(b_np) - lb_j) / (ub_j - lb_j)
                u = jnp.clip(u, 1e-12, 1.0 - 1e-12)
                return jnp.log(u / (1.0 - u))

        # --- resume fast path: skip expensive warm-start construction when a
        #   checkpoint already holds the chain state (preemption recovery) ---
        resume_state = None
        if self._resume_from:
            try:
                import os

                if os.path.exists(self._resume_from):
                    d = np.load(self._resume_from, allow_pickle=True)
                    if (int(d["X"].shape[1]) == int(obj.n_params)
                            and int(d["X"].shape[0]) == int(self.n_chains)):
                        resume_state = d
            except Exception as e:
                self.phase_log.append(f"resume_probe_failed: {e!r}")
                resume_state = None

        key, sub = jax.random.split(key)
        # Shape-only placeholder for warmup (topology-dependent work must happen
        # AFTER start_logging per submission rules). On resume we already have X.
        if resume_state is not None:
            X = jnp.asarray(resume_state["X"])
        else:
            X = jnp.zeros((self.n_chains, obj.n_params))

        B, n = X.shape
        ws_index = self._load_index(obj)  # free: dataset index load (no objective use)
        self._ws_index = ws_index
        # ---- free compile: pick largest chunk that fits GPU memory (probe descending),
        #   then warm every chunk shape we'll emit (incl. remainder) ----
        cs = None
        for cand in dict.fromkeys((self.chunk_size, 16, 12, 8, 6, 4, 2, 1)):
            cand = min(cand, B)
            try:
                obj.warmup_vmap_value_and_grad_aux(batch_size=cand)
                cs = cand
                break
            except Exception as e:
                self.phase_log.append(f"chunk {cand} OOM: {type(e).__name__}")
        if cs is None:
            raise RuntimeError("no feasible chunk size")
        self.phase_log.append(f"chunk_size={cs}")
        if B % cs:
            obj.warmup_vmap_value_and_grad_aux(batch_size=B % cs)
        if self.screen_pool > 0:
            try:
                obj.warmup_vmap_value_aux(batch_size=self.screen_chunk)
            except Exception as e:
                self.phase_log.append(f"screen warm failed, fallback {e!r}")
                self.screen_chunk = 8
                obj.warmup_vmap_value_aux(batch_size=self.screen_chunk)
        obj.start_logging()
        self.best_feasible_loss_algo = np.inf

        # --- post-logging: topology-dependent warm start (rules-compliant) ---
        if resume_state is None:
            t_ws = time.perf_counter()
            starts_b = self._build_starts(obj, sub, ws=ws_index)  # (B, n) bounded
            X = _to_unbounded(starts_b)
            self.phase_log.append(f"warmstart_built_in={time.perf_counter()-t_ws:.1f}s")

        # --- init-pool screening: expand candidates, evaluate cheaply (value-only,
        #   big batches), keep the best B. Screened points are logged evals too. ---
        if resume_state is None and self.screen_pool > B:
            t_sc = time.perf_counter()
            rng_s = np.random.default_rng(int(jax.random.bits(sub)))
            want_fp = self.screen_diverse > B  # §27 diagnostics + knob
            fps = None
            if want_fp:
                C, merits, fps = self._screen_once(obj, np.asarray(X), rng_s,
                                                   self.screen_pool, (0.15, 0.4, 0.9),
                                                   collect_fp=True)
            else:
                C, merits = self._screen_once(obj, np.asarray(X), rng_s,
                                              self.screen_pool, (0.15, 0.4, 0.9))
            if self.screen_cascade > B and self.screen_pool > self.screen_cascade:
                # successive-halving at init: keep top intermediate pool, re-jitter
                # at finer sigmas around them, re-screen at full pool size.
                keep1 = np.argsort(merits)[: self.screen_cascade]
                if want_fp:
                    C, merits, fps = self._screen_once(obj, C[keep1], rng_s,
                                                       self.screen_pool, (0.05, 0.15, 0.4),
                                                       collect_fp=True)
                else:
                    C, merits = self._screen_once(obj, C[keep1], rng_s,
                                                  self.screen_pool, (0.05, 0.15, 0.4))
            if self.screen_diverse > B:
                # QD-style screening: shortlist the best screen_diverse by value,
                # then greedy max-min (farthest-point) B among them. Metric space
                # is normalized params (v50 lineage), or — screen_fp=pure/hybrid —
                # the behavioral fingerprint / z-scored concat of both (§27).
                cand = np.argsort(merits)[: self.screen_diverse]
                lb_s = np.asarray(obj.bounds[0])
                rng_s2 = np.asarray(obj.bounds[1]) - lb_s
                Cn = (C[cand] - lb_s[None, :]) / rng_s2[None, :]
                Fz = None
                if fps is not None:
                    F = fps[cand]
                    mu = F.mean(axis=0)
                    sd = F.std(axis=0)
                    sd[sd < 1e-12] = 1.0
                    Fz = (F - mu) / sd
                M_sel = Cn
                if Fz is not None and self.screen_fp == "pure":
                    M_sel = Fz
                elif Fz is not None and self.screen_fp == "hybrid":
                    cmu = Cn.mean(axis=0)
                    csd = Cn.std(axis=0)
                    csd[csd < 1e-12] = 1.0
                    M_sel = np.concatenate([(Cn - cmu) / csd, Fz], axis=1)
                chosen = [0]  # best-value candidate
                dmin = np.linalg.norm(M_sel - M_sel[0][None, :], axis=1)
                while len(chosen) < B:
                    j = int(np.argmax(dmin))
                    chosen.append(j)
                    dmin = np.minimum(dmin, np.linalg.norm(M_sel - M_sel[j][None, :], axis=1))
                keep = cand[np.asarray(chosen)]
                if Fz is not None:
                    # §27 diagnostics (pure logging, no numeric side effects):
                    # shortlist feasibility, fingerprint effective rank, and the
                    # overlap between the param-space and fingerprint-space picks.
                    try:
                        feas_frac = float(np.mean(merits[cand] < 1e3))
                        ev = np.clip(np.linalg.eigvalsh(np.cov(Fz.T)), 0, None)
                        pr = float(ev.sum() ** 2 / max((ev ** 2).sum(), 1e-12))
                        ch0 = [0]
                        dm0 = np.linalg.norm(Fz - Fz[0][None, :], axis=1)
                        while len(ch0) < B:
                            j0 = int(np.argmax(dm0))
                            ch0.append(j0)
                            dm0 = np.minimum(dm0, np.linalg.norm(Fz - Fz[j0][None, :], axis=1))
                        ov = len(set(ch0) & set(chosen))
                        self.phase_log.append(
                            f"screen_fp: feas={feas_frac:.2f} pr={pr:.1f} "
                            f"overlap={ov}/{B} mode={self.screen_fp or 'param'}")
                    except Exception:
                        pass
            else:
                keep = np.argsort(merits)[:B]
            X = jnp.asarray(C[keep])
            self.phase_log.append(
                f"screen: pool={self.screen_pool} cascade={self.screen_cascade} "
                f"in {time.perf_counter()-t_sc:.0f}s, "
                f"best {merits[keep[0]]:.3f} med {np.median(merits):.3f}")

        m = jnp.zeros_like(X)
        v = jnp.zeros_like(X)
        best_x = np.array(X)  # per-chain best (unbounded)
        best_merit = np.full(B, np.inf)
        ema_x = np.array(X) if self.polyak_ema > 0 else None
        resumed = False
        if resume_state is not None:
            try:
                d = resume_state
                X = jnp.asarray(d["X"])
                m = jnp.asarray(d["m"])
                v = jnp.asarray(d["v"])
                best_x = np.asarray(d["best_x"])
                best_merit = np.asarray(d["best_merit"])
                self.best_feasible_loss_algo = float(d["best_feasible"][0])
                step0 = int(d["step"][0])
                self._es_sigma = float(d["es_sigma"][0])
                selected = set(np.asarray(d["selected"]).tolist())
                if ema_x is not None and "ema_x" in d:
                    ema_x = np.asarray(d["ema_x"])
                key = jax.random.wrap_key_data(d["key_data"])
                self.cum_time_prev = float(d["cum_time"][0])
                self.phase_log = list(np.asarray(d["phase_log"]).tolist())
                if "traj" in d and len(d["traj"]):
                    self._traj = [list(r) for r in np.asarray(d["traj"]).tolist()]
                if "kick_roi" in d:
                    self._kick_roi_fails = int(d["kick_roi"][0])
                    self._gb_at_last_kick = float(d["kick_roi"][1])
                    if len(d["kick_roi"]) > 2:
                        self._kick_sched_idx = int(d["kick_roi"][2])
                    if len(d["kick_roi"]) > 3:
                        self._kick_sched_idx_d2 = int(d["kick_roi"][3])
                if "chain_kick_prog" in d and len(d["chain_kick_prog"]) == B:
                    self._chain_kick_prog = np.asarray(d["chain_kick_prog"], dtype=float)
                if "lr_mult" in d and len(d["lr_mult"]) == B:
                    self._lr_mult = np.asarray(d["lr_mult"], dtype=float)
                    self._tr_ref = best_merit.copy()
                resumed = True
                self.phase_log.append(f"resumed from {self._resume_from} step={step0} cum_prev={self.cum_time_prev:.0f}s")
            except Exception as e:
                self.phase_log.append(f"resume_failed: {e!r}")
        es_count = int(round(B * self.es_frac))
        if es_count > 0:
            self.phase_log.append(f"es_stream: {es_count}/{B} chains")
        step = 0
        t0 = time.perf_counter()
        # global budget-progress across preemption resumes: obj's fraction is
        # per-session (max_time was shrunk by cum_time on resume), so after a
        # resume every prog-spaced schedule (kicks/selects/lr) would otherwise
        # re-fire at wrong global times. Uninterrupted runs are unaffected.
        if self.resume_prog_fix:
            self._obj_max_time = float(getattr(obj, "_max_time", None)
                                       or getattr(obj, "max_time", None) or 0.0)
        if not resumed:
            selected = set()
        else:
            step = step0

        while not obj.budget_exceeded:
            step += 1
            losses, grads, feas_j, pen_j = self._chunked_vg_aux(obj, X, cs)
            losses_np = np.asarray(losses, dtype=np.float64)
            feas_np = np.asarray(feas_j, dtype=bool)
            pen_np = np.asarray(pen_j, dtype=np.float64)

            # --- merit & per-chain best tracking ---
            merit = np.where(feas_np, losses_np, 1e3 + pen_np)
            merit = np.where(np.isfinite(merit), merit, np.inf)
            f_ok = feas_np & np.isfinite(losses_np)
            if np.any(f_ok):
                self.best_feasible_loss_algo = min(self.best_feasible_loss_algo,
                                                   float(np.min(losses_np[f_ok])))
            if step == 1:
                self.phase_log.append(
                    f"init merit: min={np.min(merit):.3f} p25={np.percentile(merit, 25):.3f} "
                    f"med={np.median(merit):.3f} n_feasible={int(feas_np.sum())}/{len(feas_np)}")
            better = merit < best_merit
            if np.any(better):
                best_merit[better] = merit[better]
                best_x[better] = np.asarray(X)[better]

            # --- Adam update ---
            g = jnp.where(jnp.isfinite(grads), grads, 0.0)
            gnorm = jnp.linalg.norm(g, axis=1, keepdims=True)
            g = g * jnp.minimum(1.0, self.grad_clip / (gnorm + 1e-12))
            m = self.b1 * m + (1 - self.b1) * g
            v = self.b2 * v + (1 - self.b2) * g * g
            mhat = m / (1 - self.b1 ** step)
            vhat = v / (1 - self.b2 ** step)

            prog = obj.budget_progress_fraction
            if self.resume_prog_fix and self.cum_time_prev > 0 and self._obj_max_time > 0:
                prog = min(1.0, (self.cum_time_prev + (time.perf_counter() - t0))
                           / (self.cum_time_prev + self._obj_max_time))
            if self.deme2_frac > 0 and self._deme1 is None:
                # positional deme split (ES-stream / sigma_ladder idiom): the last
                # round(B*deme2_frac) slots run regime B (deme2_kick_schedule /
                # deme2_adaptive), the rest keep the v37 adaptive regime.
                n_d2 = int(round(len(best_merit) * self.deme2_frac))
                self._deme1 = np.zeros(len(best_merit), dtype=bool)
                if n_d2 > 0:
                    self._deme1[-n_d2:] = True
                self.phase_log.append(f"demes: d0={int((~self._deme1).sum())} d1={int(self._deme1.sum())} select={self.deme_select}")
            if self.tr_window_prog > 0:
                # per-chain trust regions (TuRBO lineage, §21): each chain's lr
                # multiplier adapts to its own progress — stagnant chains widen
                # (in-basin escape hatch; basin escape itself is owned by kicks),
                # improving chains shrink (exploit). Never touches X or moments,
                # so young basins are unharmed by construction (§19b constraint).
                if self._lr_mult is None:
                    self._lr_mult = np.ones(len(best_merit))
                    self._tr_ref = np.full(len(best_merit), np.inf)
                if float(prog) - self._tr_last_prog >= self.tr_window_prog:
                    self._tr_last_prog = float(prog)
                    fin = np.isfinite(self._tr_ref)
                    improved = fin & (best_merit < self._tr_ref - 1e-6)
                    stagnant = fin & ~improved
                    self._lr_mult[improved] *= self.tr_shrink
                    self._lr_mult[stagnant] *= self.tr_grow
                    self._lr_mult = np.clip(self._lr_mult, self.tr_lo, self.tr_hi)
                    self._tr_ref = best_merit.copy()
            if self.select_rule == "extrap" and step % 20 == 0:
                self._chain_hist.append((float(prog), best_merit.copy()))
            # decay_onset: WSD-style stable phase before cooldown (Hägele et al.
            # NeurIPS 2024 — constant LR then ~20% cooldown matches full decay).
            # onset=0 → q=prog → legacy from-start linear decay (bit-identical).
            if self.restart_fracs:
                # SGDR-style warm restarts: segmented linear decay. Each restart
                # re-peaks lr at restart_lr_frac of base and decays to the next
                # restart point (or 1.0) — a second exploration phase that can
                # break the monoculture plateau on stuck seeds.
                s, peak = 0.0, self.lr
                for r in self.restart_fracs:
                    if prog >= r:
                        s, peak = r, self.lr * self.restart_lr_frac
                nxt = [r for r in self.restart_fracs if r > prog]
                e = nxt[0] if nxt else 1.0
                q = min(1.0, max(0.0, (prog - s) / max(e - s, 1e-9)))
                lr_t = peak * (self.lr_final_frac + (1 - self.lr_final_frac) * (1 - q))
            else:
                q = 1.0 if self.decay_onset >= 1.0 else min(1.0, max(0.0, (prog - self.decay_onset) / (1.0 - self.decay_onset)))
                lr_t = self.lr * (self.lr_final_frac + (1 - self.lr_final_frac) * (1 - q))
            sig_t = self.noise_final + (self.noise0 - self.noise_final) * max(0.0, 1 - prog / self.noise_decay_prog)
            if self.tr_window_prog > 0:
                upd = (lr_t * jnp.asarray(self._lr_mult)[:, None]) * mhat / (jnp.sqrt(vhat) + self.eps)
            else:
                upd = lr_t * mhat / (jnp.sqrt(vhat) + self.eps)
            X = X - upd

            key, sub = jax.random.split(key)
            # temperature ladder (parallel-tempering spirit, sans swaps): fixed
            # per-slot noise scales, geometric from tight to wide, mean-preserving.
            if self.sigma_ladder > 0:
                if not hasattr(self, "_sig_scale"):
                    B_ = X.shape[0]
                    r = float(np.sqrt(self.sigma_ladder))
                    sc = np.geomspace(1.0 / r, r, B_)
                    sc /= sc.mean()
                    self._sig_scale = jnp.asarray(sc[:, None])
                    self.phase_log.append(f"sigma_ladder R={self.sigma_ladder} "
                                          f"range=[{sc[0]:.3f},{sc[-1]:.3f}]")
                X = X + (sig_t * self._sig_scale) * jax.random.normal(sub, X.shape)
            else:
                X = X + sig_t * jax.random.normal(sub, X.shape)

            # --- ES stream: last es_count chains explore around the elite mean ---
            if es_count > 0:
                order_es = np.argsort(best_merit)
                elite_idx = order_es[: self.es_top_m]
                # adapt sigma from THIS eval's ES performance (placed last step)
                es_merit_now = merit[-es_count:]
                if step > 1 and np.all(np.isfinite(best_merit[elite_idx])):
                    if np.any(es_merit_now <= np.max(best_merit[elite_idx])):
                        self._es_sigma = min(self._es_sigma * 1.22, self.es_sigma_max)
                    else:
                        self._es_sigma = max(self._es_sigma * 0.82, self.es_sigma_min)
                elite_mean = np.mean(best_x[elite_idx], axis=0)
                key, sub = jax.random.split(key)
                es_new = elite_mean[None, :] + self._es_sigma * jax.random.normal(sub, (es_count, n))
                X = jnp.concatenate([X[:-es_count], es_new], axis=0)

            # --- NaN rescue: reset broken chains to their best ---
            bad = ~np.all(np.isfinite(np.asarray(X)), axis=1) | ~np.isfinite(losses_np)
            if np.any(bad):
                Xnp = np.array(X, copy=True)
                for i in np.where(bad)[0]:
                    if np.isfinite(best_merit[i]):
                        Xnp[i] = best_x[i] + 0.1 * np.random.default_rng(i + step).standard_normal(n)
                    else:
                        lb, ub = np.asarray(obj.bounds[0]), np.asarray(obj.bounds[1])
                        rb = np.random.default_rng(i * 7919 + step).uniform(lb, ub)
                        Xnp[i] = np.asarray(_to_unbounded(rb[None, :]))[0]
                X = jnp.asarray(Xnp)

            # --- Polyak/schedule-free-style iterate averaging: the EMA point is a
            # nearly-free extra candidate per chain (value-only evals, logged).
            # Halflife is in budget-progress space (hardware-robust). ---
            if ema_x is not None:
                dprog = max(0.0, float(prog) - self._ema_prev_prog)
                self._ema_prev_prog = float(prog)
                alpha = 0.5 ** (dprog / self.polyak_ema)
                ema_x = alpha * ema_x + (1.0 - alpha) * np.asarray(X)
                if float(prog) - self._ema_eval_prog >= self.polyak_cadence:
                    self._ema_eval_prog = float(prog)
                    emer = self._merit_chunked(obj, jnp.asarray(ema_x))
                    better_e = emer < best_merit
                    if np.any(better_e):
                        best_merit[better_e] = emer[better_e]
                        best_x[better_e] = ema_x[better_e]

            # --- selection: replace worst with copies of best (+noise) ---
            for sf in self.select_fracs:
                if sf not in selected and prog >= sf:
                    selected.add(sf)
                    # freeze-thaw style ranking: extrapolate each chain's learning
                    # curve to end-of-budget (robust slope in log-prog space) so a
                    # late-blooming basin is not killed for being behind *now*.
                    score = best_merit if self.select_rule != "extrap" \
                        else self._extrap_score(best_merit, float(prog))
                    order = np.argsort(score)
                    if self._deme1 is not None and self.deme_select == "within":
                        # within-deme selection: each deme keeps its own elites and
                        # culls its own worst — a global select would hand deme 1's
                        # slots to deme 0's elites in a single event (agent-19 Q1),
                        # collapsing the portfolio. Demes evolve in parallel.
                        segs = []
                        for mask in (~self._deme1, self._deme1):
                            idx = np.where(mask)[0]
                            order_d = idx[np.argsort(score[idx], kind="stable")]
                            half_d = max(1, int(round(len(idx) * self.select_keep_frac)))
                            elite_d, worst_d = order_d[:half_d], order_d[half_d:]
                            if self.kick_protect_prog > 0:
                                fresh = (prog - self._chain_kick_prog[worst_d]) < self.kick_protect_prog
                                worst_d = worst_d[~fresh]
                            segs.append((elite_d, worst_d))
                    else:
                        half = max(1, int(round(B * self.select_keep_frac)))
                        elite, worst = order[:half], order[half:]
                        if self.kick_protect_prog > 0:
                            # grace period for freshly kicked chains: best_merit resets
                            # to inf at injection, so without protection the next select
                            # slaughters basins before they can mature (§18). Skip them
                            # here (fewer replacements, never dig into elites).
                            fresh = (prog - self._chain_kick_prog[worst]) < self.kick_protect_prog
                            worst = worst[~fresh]
                        segs = [(elite, worst)]
                    Xnp = np.array(X, copy=True)
                    rng = np.random.default_rng(step)
                    replaced = []
                    for elite_s, worst_s in segs:
                        if len(worst_s) == 0:
                            continue
                        replaced.append(worst_s)
                        n_x = int(round(len(worst_s) * self.crossover_frac))
                        if n_x > 0:
                            # component-wise crossover between two random elites
                            if self._groups is None:
                                self._groups = _position_groups(obj._problem._optimization_pairs)
                            ea = rng.integers(0, len(elite_s), size=n_x)
                            eb = rng.integers(0, len(elite_s), size=n_x)
                            pa, pb = best_x[elite_s[ea]], best_x[elite_s[eb]]
                            # per-GROUP coin flip: take that component group from parent B
                            group_pick = rng.random((n_x, self._groups.max() + 1)) < 0.5
                            choose_b = group_pick[:, self._groups]
                            child = np.where(choose_b, pb, pa)
                            Xnp[worst_s[:n_x]] = child + 0.02 * rng.standard_normal((n_x, n))
                            worst_s = worst_s[n_x:]
                        Xnp[worst_s] = best_x[elite_s[: len(worst_s)]] + 0.05 * rng.standard_normal((len(worst_s), n))
                    replaced = np.concatenate(replaced) if replaced else np.array([], dtype=int)
                    X = jnp.asarray(Xnp)
                    if self.select_keep_moments:
                        # PBT-style warm start: survivors keep their Adam moments
                        # (their X is unchanged, so m/v stay valid); only chains
                        # whose X was overwritten restart the optimizer state.
                        mnp = np.array(m, copy=True)
                        vnp = np.array(v, copy=True)
                        mnp[replaced] = 0.0
                        vnp[replaced] = 0.0
                        m = jnp.asarray(mnp)
                        v = jnp.asarray(vnp)
                    else:
                        m = jnp.zeros_like(X)
                        v = jnp.zeros_like(X)
                    self.phase_log.append(
                        f"select@{prog:.2f} step={step} best_merit={best_merit[order[0]]:.4f} "
                        f"med={np.median(best_merit):.4f} elapsed={time.perf_counter()-t0:.0f}s")

            # --- stagnation kick: inject fresh donor basins into stagnant worst chains ---
            # Scheduling lives in *budget-progress* space when kick_patience_prog > 0
            # (hardware-robust: eval contract is wall-clock, step rates vary ~10x
            # across GPUs). Late kicks are skipped: an injected basin needs enough
            # remaining budget to refine, so kicking past kick_max_prog is futile.
            if (self.kick_patience > 0 or self.kick_patience_prog > 0 or self.kick_schedule
                or (self._deme1 is not None and (self.deme2_kick_schedule or self.deme2_adaptive))) and \
                    (self._ws_index is not None or self.kick_mode == "elite"):
                gb = float(np.min(best_merit))

                def _do_kick(kick_idx, elite_src, force_elite=False):
                    nonlocal X, m, v
                    ws = self._ws_index
                    Xnp = np.array(X, copy=True)
                    rng = np.random.default_rng(step * 131 + 7)
                    n_new = 0

                    # elite hop: perturb a top chain's best with large sigma
                    # (basin hopping from the incumbent — right move when all
                    # donors are far and their basins are worse than ours)
                    def _hop(j, ci):
                        src = best_x[elite_src[j % len(elite_src)]]
                        Xnp[ci] = src + self.elite_hop_sigma * rng.standard_normal(n)

                    if force_elite:
                        mode = "elite"  # FunSearch-style cull-reseed: ignore donor mode
                    else:
                        mode = self.kick_mode if self._ws_index is not None else "elite"
                    if mode == "elite":
                        for j, ci in enumerate(kick_idx):
                            _hop(j, ci)
                            n_new += 1
                        donors = None
                    else:
                        donors = ws.nearest_donors(obj._problem.topology_string,
                                                   k=self.kick_donor_pool,
                                                   interior_weight=self.interior_weight,
                                                   loss_weight=self.donor_loss_weight)
                        if self.kick_novelty and donors:
                            counts = [self._donor_used.get((t, e), 0) for t, _d, _l, e in donors]
                            mn = min(counts)
                            if prog > self.kick_max_prog and mn > 0:
                                donors = None  # late region: all pool basins already
                                # visited — a late kick would re-cover old ground; skip
                            else:
                                donors = [d for d, c in zip(donors, counts) if c == mn]
                        if donors is not None:
                            aux = self._aux_kvs(ws, donors)
                    if mode == "mix" and donors is not None:
                        for j, ci in enumerate(kick_idx):
                            if j % 2 == 1:
                                _hop(j, ci)
                            else:
                                di = self._pick_donor(donors)
                                topo, dist, dloss, eidx = donors[di]
                                self._mark_donor(donors[di])
                                v = ws.transplant(obj._problem, topo, eidx, fill=self.fill_mode, aux_kvs=aux)
                                Xnp[ci] = np.asarray(_to_unbounded(v[None, :]))[0] + self._ksig(j) * rng.standard_normal(n)
                            n_new += 1
                    elif donors is not None and self.surr_kick:
                        # surrogate-ranked kick: transplant the whole donor pool,
                        # keep the candidates the surrogate likes most (replaces
                        # cycle/diverse selection with predicted quality)
                        cands, cd = [], []
                        for donor in donors:
                            topo, dist, dloss, eidx = donor
                            try:
                                cands.append(np.asarray(ws.transplant(obj._problem, topo, eidx, fill=self.fill_mode, aux_kvs=aux),
                                                        dtype=np.float64))
                                cd.append(donor)
                            except Exception:
                                continue
                        sc = surrogate_score(obj._problem, np.asarray(cands)) if cands else None
                        order_k2 = np.argsort(sc) if sc is not None else np.arange(len(cd))
                        for j, ci in enumerate(kick_idx):
                            if j >= len(cd):
                                break
                            self._mark_donor(cd[order_k2[j]])
                            Xnp[ci] = np.asarray(_to_unbounded(cands[order_k2[j]][None, :]))[0] + self._ksig(j) * rng.standard_normal(n)
                            n_new += 1
                    elif donors is not None and self.kick_diverse:
                        # farthest-point sampling among transplanted candidates:
                        # pick donors whose bounded vectors are farthest from the
                        # chains we keep (and from each other) — basin diversity.
                        lb_k, ub_k = np.asarray(obj.bounds[0]), np.asarray(obj.bounds[1])
                        rng_k = ub_k - lb_k
                        cands = []
                        cand_donors = []
                        for donor in donors:
                            topo, dist, dloss, eidx = donor
                            try:
                                cands.append(np.asarray(ws.transplant(obj._problem, topo, eidx, fill=self.fill_mode, aux_kvs=aux),
                                                        dtype=np.float64))
                                cand_donors.append(donor)
                            except Exception:
                                continue
                        if cands:
                            Cb = (np.asarray(cands) - lb_k[None, :]) / rng_k[None, :]
                            Xb = 1.0 / (1.0 + np.exp(-np.asarray(X)))
                            keep_mask = np.ones(B, dtype=bool)
                            keep_mask[kick_idx] = False
                            ref = Xb[keep_mask]
                            avail = list(range(len(Cb)))
                            for j, ci in enumerate(kick_idx):
                                if not avail:
                                    break
                                d = np.linalg.norm(
                                    Cb[avail][:, None, :] - ref[None, :, :], axis=-1
                                ).min(axis=1)
                                pick = avail.pop(int(np.argmax(d)))
                                self._mark_donor(cand_donors[pick])
                                Xnp[ci] = np.asarray(_to_unbounded(cands[pick][None, :]))[0] \
                                    + self._ksig(j) * rng.standard_normal(n)
                                ref = np.concatenate([ref, Cb[pick][None, :]], axis=0)
                                n_new += 1
                    elif donors is not None:
                        for j, ci in enumerate(kick_idx):
                            di = self._pick_donor(donors)
                            topo, dist, dloss, eidx = donors[di]
                            self._mark_donor(donors[di])
                            v = ws.transplant(obj._problem, topo, eidx, fill=self.fill_mode, aux_kvs=aux)
                            Xnp[ci] = np.asarray(_to_unbounded(v[None, :]))[0] + self._ksig(j) * rng.standard_normal(n)
                            n_new += 1
                    X = jnp.asarray(Xnp)
                    m = jnp.where(jnp.isin(np.arange(B), kick_idx)[:, None], 0.0, m)
                    v = jnp.where(jnp.isin(np.arange(B), kick_idx)[:, None], 0.0, v)
                    best_merit[kick_idx] = np.inf
                    self._chain_kick_prog[kick_idx] = prog
                    if self.tr_window_prog > 0 and self._lr_mult is not None:
                        # fresh basin: reset TR state so stale multipliers
                        # don't leak across the injected donor landscape
                        self._lr_mult[kick_idx] = 1.0
                        self._tr_ref[kick_idx] = np.inf
                    self.phase_log.append(
                        f"kick@step={step} prog={prog:.2f} mode={mode} injected {n_new} (cycle={self._donor_cycle}) gb={gb:.4f}"
                        + (f" fails={self._kick_roi_fails}" if self.kick_roi_gate else ""))

                if self._deme1 is not None:
                    # deme mode: each deme keeps its own stagnation clock / schedule
                    # and kicks its own worst chains (portfolio isolation, §19f).
                    for d, mask in ((0, ~self._deme1), (1, self._deme1)):
                        idx = np.where(mask)[0]
                        if len(idx) == 0:
                            continue
                        fire = False
                        if ((d == 0) or self.deme2_adaptive) and self.kick_patience_prog > 0:
                            gb_d = float(np.min(best_merit[idx]))
                            if gb_d < self._gb_prev_d[d] - 1e-6:
                                self._gb_prev_d[d] = gb_d
                                self._last_improve_prog_d[d] = float(prog)
                            elif ((prog - self._last_improve_prog_d[d]) >= self.kick_patience_prog
                                  and prog > 0.03 and prog <= self.kick_max_prog):
                                fire = True
                                self._last_improve_prog_d[d] = float(prog)
                        if d == 1 and self.deme2_kick_schedule:
                            while (self._kick_sched_idx_d2 < len(self.deme2_kick_schedule)
                                   and prog >= self.deme2_kick_schedule[self._kick_sched_idx_d2]):
                                self._kick_sched_idx_d2 += 1
                                if prog <= self.kick_max_prog:
                                    fire = True
                        if fire:
                            order_d = idx[np.argsort(best_merit[idx], kind="stable")]
                            # deme2_cull_frac>0 (deme1 only): FunSearch-style deep cull —
                            # reseed the worst cull_frac of the deme from its own best
                            # (force_elite hops), instead of the default shallow kick_frac.
                            frac_d = self.deme2_cull_frac if (d == 1 and self.deme2_cull_frac > 0) else self.kick_frac
                            elite_d = d == 1 and self.deme2_kick_elite
                            n_kick_d = max(1, int(round(len(idx) * frac_d)))
                            _do_kick(order_d[-n_kick_d:], order_d[: max(1, len(idx) // 8)],
                                     force_elite=elite_d)
                else:
                    # scheduled coverage kicks (kick_schedule: fixed prog points, fire even
                    # while improving — Mode-A early-window coverage, §12b/§16). Resume-safe:
                    # _kick_sched_idx persists in kick_roi[2]. Default () = bit-identical.
                    sched_due = False
                    if self.kick_schedule:
                        while (self._kick_sched_idx < len(self.kick_schedule)
                               and prog >= self.kick_schedule[self._kick_sched_idx]):
                            self._kick_sched_idx += 1
                            sched_due = True
                    if gb < self._global_best_prev - 1e-6 and not sched_due:
                        self._global_best_prev = gb
                        self._last_improve_step = step
                        self._last_improve_prog = prog
                    else:
                        if self.kick_patience_prog > 0:
                            eff_pat = self.kick_patience_prog
                            if self.kick_roi_gate:
                                eff_pat = self.kick_patience_prog * min(
                                    self.kick_roi_cap,
                                    self.kick_roi_backoff ** self._kick_roi_fails)
                            if self.kick_patience_stretch > 0:
                                eff_pat = eff_pat * (1.0 + self.kick_patience_stretch * prog)
                            due = (prog - self._last_improve_prog) >= eff_pat and prog > 0.03
                        else:
                            due = step - self._last_improve_step >= self.kick_patience and step > 50
                        if not (self.kick_patience > 0 or self.kick_patience_prog > 0):
                            due = False  # schedule-only configs must not fire every step
                        late_novel = (self.kick_novelty
                                      and self.kick_max_prog_novel > self.kick_max_prog
                                      and prog <= self.kick_max_prog_novel)
                        if (due or sched_due) and (prog <= self.kick_max_prog or late_novel):
                            if self.kick_roi_gate:
                                if gb < self._gb_at_last_kick - 1e-6:
                                    self._kick_roi_fails = 0
                                else:
                                    self._kick_roi_fails += 1
                                self._gb_at_last_kick = gb
                            self._last_improve_step = step
                            self._last_improve_prog = prog
                            n_kick = max(1, int(round(B * self.kick_frac)))
                            order_k = np.argsort(best_merit)
                            _do_kick(order_k[-n_kick:], order_k[: max(1, B // 8)])

            if self._ckpt_path and (time.perf_counter() - t0 + 0.0) - (self._ckpt_last - 0.0) >= self._ckpt_interval:
                self._ckpt_last = time.perf_counter() - t0
                try:
                    self._save_ckpt(X, m, v, best_x, best_merit, step, selected, key,
                                    self.cum_time_prev + self._ckpt_last, ema_x=ema_x)
                except Exception as e:
                    self.phase_log.append(f"ckpt_failed: {e!r}")

            if step % 10 == 0:
                self._traj.append([round(self.cum_time_prev + (time.perf_counter() - t0), 1),
                                   round(float(np.min(best_merit)), 5)])

            if (self.polish_start > 0 and prog >= self.polish_start
                    and np.isfinite(self.best_feasible_loss_algo)):
                self.phase_log.append(f"enter polish at prog={prog:.2f} step={step}")
                break
            if step % self.phase_log_every == 0:
                self.phase_log.append(
                    f"step={step} prog={prog:.2f} best={np.min(best_merit):.4f} "
                    f"med={np.median(best_merit):.4f} lr={lr_t:.4f} sig={sig_t:.3f}")

        # ---------------- L-BFGS polish on the best chain ----------------
        if self.polish_start > 0 and np.isfinite(self.best_feasible_loss_algo):
            try:
                self._lbfgs_polish(obj, best_x[int(np.argmin(best_merit))], n)
            except Exception as e:
                self.phase_log.append(f"polish_failed: {e!r}")

    def _lbfgs_polish(self, obj, x0, n):
        """Optax L-BFGS on the best point; logs via value_and_grad_aux for scoring."""
        import optax

        x = jnp.asarray(x0, dtype=jnp.float32)
        value_fn = obj.value_function(unbounded=True)
        vg_fn = jax.jit(jax.value_and_grad(value_fn))
        opt = optax.lbfgs()
        st = opt.init(x)
        step_ct = 0
        while not obj.budget_exceeded:
            step_ct += 1
            loss_j, g = vg_fn(x)
            upd, st = opt.update(g, st, x, value=loss_j, grad=g, value_fn=value_fn)
            x = optax.apply_updates(x, upd)
            l, _g, a = obj.value_and_grad_aux(x)  # logged with feasibility
            la = float(np.asarray(l))
            fa = bool(np.asarray(a["is_feasible"]))
            if fa and np.isfinite(la):
                self.best_feasible_loss_algo = min(self.best_feasible_loss_algo, la)
            if step_ct % 20 == 0:
                self.phase_log.append(f"polish step={step_ct} loss={la:.4f} feas={fa}")


# ---- baked submission hyperparameters (single-class rule) ----
import json as _json

_BAKED_KWARGS = _json.loads('{"lr": 0.2, "n_chains": 16, "n_transplant": 96, "screen_pool": 1024, "kick_patience_prog": 0.05, "kick_max_prog": 0.6, "kick_diverse": true, "donor_loss_weight": 0.5, "select_fracs": [0.3, 0.5, 0.7, 0.85], "resume_prog_fix": true, "noise0": 0.0, "noise_final": 0.0, "screen_diverse": 64, "kick_protect_prog": 0.1, "deme2_frac": 0.5, "deme2_kick_schedule": [0.32, 0.52], "deme_select": "within"}')
_orig_init_ParallelAdamSubmission = ParallelAdamSubmission.__init__


def _baked_init_ParallelAdamSubmission(self, **kw):
    merged = dict(_BAKED_KWARGS)
    merged.update(kw)
    _orig_init_ParallelAdamSubmission(self, **merged)


ParallelAdamSubmission.__init__ = _baked_init_ParallelAdamSubmission
ParallelAdamSubmission.algorithm_str = "parallel_adam_submission"
